[package]
name = "huangli-quick-search"
version = "0.1.0"
description = "Huangli quick search"
edition = "2021"

[lib]
name = "huangli_quick_search_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
